### ISSUE TITLE
Support for precompiled R packages

### ISSUE THREAD

**Issue by sdebruyn** [rocker-org/rocker-versioned2#102]
According to the current documentation, you can't use precompiled ubuntu cran packages. Is there a way I can use your R Studio setup for Docker and still use the precompiled packages?

I have to install 50+ packages and their dependencies and compiling all of these takes a very long time.

**Comment by eddelbuettel** [comment]
Yes please see e.g. rocker/r-rspm and rocker/r-bspm which do just that relying on, at your choice, RSPM or BSPM.  I have used the Ubuntu PPA _for years_ and have numerous blog posts below http://dirk.eddelbuettel.com/blog/code/r4/ which show just that -- the older ones relying on explicit `apt install r-cran-$PACKAGENAME` which the BSPM solution (which I for example also use in my use of CI, see https://eddelbuettel.github.io/r-ci/ and short video and slides at the most recent r4 entry from above).  There are various demos showing _e.g._ `rstan` installations in a mere minute or two when using binaries.  I agree with you that path is in fact preferable.  (And I happen to have a weak preference of BSPM over RSPM because .deb binaries do have full dependencies which is harder to do for RSPM which completements by covering more architectures and distributions, but that is irrelevant for Docker...)

Now, rocker's r-versioned stuff is different by design and on purposes and we do not have a similar 'two-dimensional grid' of packages versions through time for binaries so it;s trade-offs.   But you could build on the above and just load r-studio yourself in a local or personal Dockerfile.

**Comment by sdebruyn** [comment]
Alright, thanks for the clarification! I was using my own mirror everywhere instead of using the default one. Removing my own mirror from the R installation dramatically increased the speed of my docker build.

**Comment by eddelbuettel** [comment]
Yeah, that would do it.  :)
