### ISSUE TITLE
Why compile R instead of using CRAN repositories?

### ISSUE THREAD

**Issue by Picea** [rocker-org/rocker-versioned2#114]
Dear rocker team,

Thanks a lot for making available these high-quality docker images. Your hard work and expertise is really appreciated here!

I have read some of your dockerfiles, for example the r-ver and shiny ones, and got a question: what is the purpose of compiling R instead of using the Ubuntu repositories from the CRAN?

I assume that, for someone like me that build the images from your dockerfiles, it could perhaps make R a bit faster with some CPU or kernel optimizations (I am not sure how Docker handle this though)? Do I miss something here?

Again, thanks a lot for all your work!

**Comment by eddelbuettel** [comment]
Because they are "versioned" to a point in time -- see our [R Journal paper](https://journal.r-project.org/archive/2017/RJ-2017-065/index.html) for some context.

But we also do have a lot of containers that use the Debian or Ubuntu binaries, starting from `rocker/r-base` aka the official `r-base` to many more derived ones as, say, the more recent `rocker/r-bspm` one.  

I hope this answers your question. If so, please feel free to close it.

**Comment by Picea** [comment]
Hi Dirk, thanks for your quick response and reference. Exactly what I was looking for!
