### ISSUE TITLE
Are Docker tags overwritten?

### ISSUE THREAD

**Issue by LustigePerson** [rocker-org/rocker-versioned2#126]
Hello,

I am trying to trace down a strange issue with rocker/shiny-verse running behind a reverse proxy.
The App is never starting, but the server is running. I just see a "Page not found".
However, this made no sense to me, as only the code of the app changed and I rebuilt it.
But now after hours of fiddling around I saw on Dockerhub that the tag 4.0.0 was overwritten some time ago?
So does this mean the tags are not fixed? I built my docker for the first time 6 months ago and when I use this image instead of the "current" rocker/shiny-verse:4.0.0 it works behind the proxy without issues.

So just to confirm: The docker tags ARE changing, meaning if I built something on 4.0.0 now it will not use the same Image/Packages/Installation scripts if I rebuilt it in half a year? Are there any alternative tags that stay consistent?

**Comment by cboettig** [comment]
Apologies for the trouble, the page not found does sound like a bug.

I'm not quite sure what you mean by "overwritten".  Tags are not  the same as image hashes, they merely pin versions, but they still receive the same updates (e.g .security patches) inherited upstream when re-building the image from it's Dockerfile. I believe this is standard practice, e.g. [python:3.7](https://hub.docker.com/layers/python/library/python/3.7/images/sha256-f076499641fc1fcf818749e63d3fc90dc59532f97d273c25cea2d24c8cd2df15?context=explore) was last updated 4 days ago.  To stay bitwise consistent, you would merely need to preserve the image as is.  It's the goal of the versioned stack that the _Dockerfile recipe_ should be reproducible, giving you the same version of R, same version of R packages, and fixed to a stable Linux release, so this error is indeed undesirable and we can look into it.  In contrast, the rocker/r-base stack tags do not change, r-base:4.0.0 is always bitwise identical (critical security vulnerabilities and all), _but_ cannot be bitwise recreated from any installation script today. Those scripts point to upstream sources that are changing and will not even get the same versions because it is tied to the 'rolling' debian:testing instead of a fixed release.    We discuss these issues in more detail at https://doi.org/10.32614/RJ-2017-065

So in short, I understand your frustration with the app behavior, but we need a reproducible example to try and debug.

**Comment by LustigePerson** [comment]
Ok, thanks for the clarification. Indeed I expected the tag to be persistent, i.e., bitwise identical. But this was my fault and you have good reasons to do it like you do.
It would be amazing, just in case you ever change something, if you also persist all version. Jupyter stacks is doing this very nicely. I made the experience that often dependencies (of dependencies of dependencies...) tend to suddenly brake stuff. But nevertheless, I was just unaware and hence started bug hunting with totally wrong expectations.

Regarding the bug itself: If I manage to find a standalone repo scenario I will post it. But this would be another issue then. We have it running on azure behind a reverse proxy and perhaps for some reason there is a problem with the liveness probes. Now that I know the docker image changed I will start checking what exactly changed.

Thanks again for you comment and for your nice work!
