### ISSUE TITLE
/init in rstudio image

### ISSUE THREAD

**Issue by danhalligan** [rocker-org/rocker-versioned2#154]
The `/init` script in the rstudio image (and possibly others) is as follows:

```
#!/bin/execlineb -S0

##
## load default PATH (the same that Docker includes if not provided) if it doesn't exist,
## then go ahead with stage1.
## this was motivated due to this issue:
## - https://github.com/just-containers/s6-overlay/issues/108
##


/bin/importas -D /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PATH PATH
export PATH ${PATH}
/etc/s6/init/init-stage1 $@
```

I'm fairly sure the export line should instead read:

```
export PATH="${PATH}"
```

Firstly, the `=` is necessary for assignment, and I think the quotes should be there for safety.

When altered this prevents an error I see when launching the container, which is as follows:

```
...
rstudio_1  | /init: line 12: export: `/usr/lib/rstudio-server/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin': not a valid identifier
...
```

I maybe completely wrong about this, because I only have a very vague understanding of what is going on here, so please ignore if this is not obviously an issue.

**Comment by eitsupi** [comment]
I think the script comes from here.
https://github.com/just-containers/s6-overlay/blob/e70ed90c90c66bfaa8fd64ea506b410a17371ca0/builder/overlay-rootfs/init

This is because `rocker/rstudio` uses `s6-overlay`.
https://github.com/rocker-org/rocker-versioned2/blob/391713d5d3797890d2f85c600e5520f05c5f715b/scripts/install_s6init.sh#L15

This issue may be more appropriate to post to the upstream repository, [just-containers/s6-overlay](https://github.com/just-containers/s6-overlay/).

**Comment by cboettig** [comment]
Thanks both!  :eyes: upstream

**Comment by eitsupi** [comment]
According to the upstream issue https://github.com/just-containers/s6-overlay/issues/342, this does not seem to be a problem.
So I would like to close this issue.
