### ISSUE TITLE
Some latest images point to the wrong base image

### ISSUE THREAD

**Issue by lab1702** [rocker-org/rocker-versioned2#177]
Latest update https://github.com/rocker-org/rocker-versioned2/pull/175 sets rocker/{shiny,shiny-verse,geospatial,binder}:latest to all point to rocker/verse image.

**Comment by cboettig** [comment]
@eitsupi

**Comment by cboettig** [comment]
thanks @lab1702 for catching the typo in #175.  rebuilding those now

**Comment by eitsupi** [comment]
@cboettig I noticed this mistake after the build, could you please merge #176 to rerun the build with GitHubActions?

**Comment by cboettig** [comment]
@eitsupi  I vaguely recall seeing random network failure issues as a common source of failure on gh-actions, especially on push to docker hub...  

We might want to add cron triggers to the gh-actions too, that will help keep latest in sync with CRAN etc, and it won't matter if a build fails randomly due to occasional network issues.

**Comment by eitsupi** [comment]
I would like to create an issue later as I think there are several ways to improve the workflow, including scheduled execution.

It may be a good idea to set it to retry if an error occurs during push.
https://github.com/nick-invision/retry
