### ISSUE TITLE
systemctl not found

### ISSUE THREAD

**Issue by myoung3** [rocker-org/rocker-versioned2#197]
The init system, specifically systemd via the systemctl command, seems to be the [typical way ](https://docs.rstudio.com/ide/server-pro/r-sessions.html#workspace-storage)to specify the XDG_DATA_HOME environment variable for rstudio server (this specifies the directory location for rstudio server's user cache), but systemd doesn't seem to be installed on the most recent version of geospatial (4.1.0).  This is surprising because the debian doc says [systemd is the default init system since debian 8](https://wiki.debian.org/systemd).

Is there a reason why systemd is [uninstalled](https://github.com/rocker-org/rocker-versioned2/blob/cd7ab3d61e3bece1e6eea6c0a4a0da9caa2fa236/scripts/install_verse.sh#L60)? 

How do you recommend setting environment variables for rstudio server?

**Comment by myoung3** [comment]
that current line is from here:
https://github.com/rocker-org/rocker-versioned2/issues/73
and before that, here:
https://github.com/rocker-org/rocker-versioned2/commit/02a64959b61ce78e96680d0044b2ce51683da7dd

**Comment by cboettig** [comment]
The base docker images for Ubuntu and Debian do not include any init system.  Please note that the base _docker images_ are not identical to the standard desktop/server distro.  

systemd is uninstalled in the config scripts because it gets automatically pulled in by one of the packages (I think librdf0-dev) even though it is not required for those libraries to work.  Note that you are linking to the `verse` recipe there, you will not find systemd installed or uninstalled in the previous elements of the stack (`rocker/tidyverse`, `rocker/verse`). 

An init system can be helpful for running RStudio, we use [S6 init](https://skarnet.org/software/s6/) which is much more light weight and [well suited for Docker](https://github.com/just-containers/s6-overlay).  

There's an existing issue regarding setting `XDG_DATA_HOME` for RStudio-Server in https://github.com/rocker-org/rocker-versioned2/issues/103 so I think we should move discussion over to there and close this?
