### ISSUE TITLE
versions.md, compatible versions vs pre-built versions

### ISSUE THREAD

**Issue by cboettig** [rocker-org/rocker-versioned2#2]
We should add a versions.md table like we have in the current `rocker-versioned`, https://github.com/rocker-org/rocker-versioned/blob/master/VERSIONS.md.  

Or is that effectively deprecated by the compatibility grid?  Or do we have the compatibility grid for developers and a versions.md still documenting what's pre-build and available on hub?

**Comment by noamross** [comment]
Well, we want the versions _as data_ so we should start here: https://docs.google.com/spreadsheets/d/11EHcl5i017ZWn__-PAPfT1d2GiNTGQbcfMuqyfkt-Rg/edit#gid=0, and then perhaps versions.md can be auto-generated.

Rather than try to describe what is compatible generally, I say that we try to guarantee that the version combinations in our grid, most of which will be pre-built, are compatible.

**Comment by cboettig** [comment]
Sounds good.  

Relatedly, we should document all of the configurable build ARGs somewhere (and possibly a list of all environmental variables created as well).  Obviously most of the build-args are version related, but not everything that has a version may have a build arg too

**Comment by cboettig** [comment]
>  most of which will be pre-built

good point.  We should perhaps indicate when we're just pulling a version from the standard bionic repo, vs when a version is being installed explicitly (from source/or other location).  e.g. for things like geos, we could list it as `3.6.2-bionic`

**Comment by cboettig** [comment]
stale since most of this is set by us sticking with a single LTS and no PPAs, but we should update `VERSIONS.md` for the stuff that doesn't come from apt repos (R, RStudio, s6, pandoc, etc)
