### ISSUE TITLE
Can't add Shiny Server to rocker/rstudio:4.1.0

### ISSUE THREAD

**Issue by scottflaska** [rocker-org/rocker-versioned2#200]
I'm trying to add Shiny Server to the `rocker/rstudio:4.1.0` image so that I can have RStudio Server and Shiny Server in the same development container. 

Here is my Dockerfile

```
FROM rocker/rstudio:4.1.0

RUN /rocker_scripts/install_shiny_server.sh
```

I then try to build the image with `docker build . -t test:with-shiny` but I receive the following error:
`executor failed running [/bin/sh -c /rocker_scripts/install_shiny_server.sh]: exit code: 100`

**Comment by cboettig** [comment]
@scottflaska Thanks for the bug report. Strange, I cannot reproduce that error, building the example Dockerfile you show works fine for me.  Maybe `docker pull rocker/rstudio:4.1.0` first and also share `docker info`?

Yup, in principle you should be able to use the `rocker_scripts/install_*` files to mix and match just like this, though some scripts will require some environmental variables and ports to be set.  e.g. compare the above to the `rocker/shiny` Dockerfile: https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/Dockerfile_shiny_4.1.0

**Comment by scottflaska** [comment]
@cboettig thanks for getting back to me! Doing to the `docker pull` before the build appears to have fixed my issue! Any idea why that worked? That's not my understanding of how docker should work, `FROM` in a Dockerfile should be no different.

**Comment by cboettig** [comment]
`docker build` will use a local image if it finds you already have one that matches the tag requested, rather than automatically running `docker pull` first.  No idea where you got a dud version of `rocker/rstudio:4.1.0`, could be we pushed a version that somehow didn't have exec privileges on `rocker_scripts` scripts, or maybe you built a copy locally.  (particularly relevant for a non-frozen image where changes are more likely; since 4.1.0 is currently `latest`)

But in any event, it's always best to run `docker pull` before building to ensure reproducibility relative to the latest release.  More specifically, you can report  the specific hash of your FROM image, e.g.

```
$ docker images | grep rocker
rocker/rstudio          4.1.0                             9fd5e08c093f        20 hours ago        1.92GB
```

Or `docker inspect`  (Sometimes it's also helpful to check docker version etc with `docker info`).

**Comment by scottflaska** [comment]
Ok, that was my understanding as well. I thought my local docker images were clean (I ran `docker system prune` and removed all of my existing images). Definitely a strange one, but I greatly appreciate the help and all the work you do to maintain these images - I use them all the time!

**Comment by scottflaska** [comment]
Adding the `--pull` tag to `docker build` may help someone who experiences this problem in the future [https://docs.docker.com/engine/reference/commandline/build/](url)

**Comment by cboettig** [comment]
Thanks @scottflaska !
