### ISSUE TITLE
How do I transition from rocker/ml-gpu to rocker/ml? 

### ISSUE THREAD

**Issue by rsangole** [rocker-org/rocker-versioned2#244]
# Thanks

Before I write my first issue here, I want to say a huge THANK YOU to your team. I have have been using your rocker base-R and tidyverse images to stabilize to a reproducible workflow. It's allowed me to learn how to setup my own R images from scratch - I wouldn't have been able to do it without your amazing work here. 

# The Issue

I've been battling this for a few days, trying different things out, but I feel like I'm flailing my arms in space.

## What works

This is what I'm used to, to get R + GPU working with Keras and TF:

```sh
docker run --gpus all --rm -it -p 8787:8787 -e DISABLE_AUTH=true rocker/ml-gpu
```
And that's it, Keras and TF work off the shelf.

Since I read `rocker/ml-gpu` is deprecated now, I'm trying to transition to `rocker/ml`. I'm struggling to get things working.

## Where I'm struggling

```sh
docker run --gpus all --rm -p 8787:8787 -e DISABLE_AUTH=true rocker/ml:cuda11.1
```
First I try to install Keras & Tensorflow GPU via RStudio:

```r
install.packages("keras")
library(keras)
install_keras(tensorflow = "gpu")
```
However this is not successful, resulting this error: https://gist.github.com/rsangole/54c5416cb353b2086e00120f44613632

This happens regardless of which image I pick - `ml:4.1.1` `ml:cuda11.1` or `ml:cuda10.1`.

## Questions

1. Obvious Q - What am I doing wrong? I'm spinning my wheels, so I get a feeling like I've not understood something critical in the new workflow.
1. Of all the tags listed [here](https://github.com/rocker-org/rocker-versioned2/wiki), which one do I pick?
  - I noticed I have to manually install Keras and TF from R after running the Docker. Is this right? (I expected a CUDA+ML image to have these pre-installed... am I missing something?)
  - Is there an image which has Keras + TF-GPU pre-installed?
 
## Versions

Local Machine:
- Linux Mint 20.2
- NVIDIA Driver 470.57.02
- CUDA - 11.4

**Comment by cboettig** [comment]
@rsangole sorry for the issues and thanks for the details.  

1.  The issue you're hitting is a permissions one which we can probably fix by providing better defaults. 

  Meanwhile, you can work around the permissions error by setting your own virtualenv, e.g. in your R session:

```r
keras::install_keras(tensorflow="gpu", envname= tools::R_user_dir("keras") )
```
(where I use `R_user_dir()` to just get a good default location, you can change that to any path you prefer).


Regarding which tag to use: all tags listed in the same cell of that table are just "aliases", e.g. currently `rocker/ml` is identical to `rocker/ml:4` which is identical to `rocker/ml:4.1.1-cuda10.1` etc.  Since you are up-to-date at 11.4, you probably want `rocker/ml:4.1.1-cuda11.1`.  Note that this image still needs an extra library before some tensorflow models will run happily on GPU, see https://github.com/rocker-org/rocker-versioned2/issues/235#issuecomment-916719310.

We should have both these things patched in the near future :blush:

**Comment by rsangole** [comment]
Thanks for the quick response @cboettig ! Both your proposed solutions worked perfectly!
