### ISSUE TITLE
Cannot install r-cran-igraph

### ISSUE THREAD

**Issue by Robinlovelace** [rocker-org/rocker-versioned2#28]
Not sure if this is deliberate but I was surprised at the behaviour, I can provide a reproducible example and there's a chance it may be useful. Is it intended that packages like this cannot be installed with apt?

```
docker run -it --rm rockerdev/geospatial:3.6.3 bin/bash
Unable to find image 'rockerdev/geospatial:3.6.3' locally
3.6.3: Pulling from rockerdev/geospatial
root@92856a14f1af:/# apt install r-cran-igraph
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 r-cran-igraph : Depends: r-base-core (>= 3.4.2-2ubuntu1) but it is not going to be installed
                 Depends: r-api-3.4
                 Depends: r-cran-irlba but it is not going to be installed
                 Depends: r-cran-magrittr but it is not going to be installed
                 Depends: r-cran-matrix but it is not going to be installed
                 Depends: r-cran-pkgconfig (>= 2.0.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by cboettig** [comment]
Okay, binary installation on linux has it's own woes, apologies I didn't think about this sooner.  We haven't added Michael Rutter's ppa yet, so apt get is just finding the R binaries that are available in the standard ubuntu:bionic release, which of course match the default R version from that release, 3.4, and not the latest release we install from the upstream mirror.  

```
apt install -y software-properties-common
add-apt-repository --enable-source --yes "ppa:marutter/c2d4u3.5"
add-apt-repository --enable-source --yes "ppa:marutter/rrutter3.5"
```

should fix this, we'll add it into `r-ver`.  thanks for the report.

**Comment by cboettig** [comment]
I'm still a bit hesitant about the PPAs since I don't think they will version-lock -- i.e. a Dockerfile built on rocker/r-ver:4.0.0 that installs R packages from the PPA binary might continue to update those packages as they are updated on the PPA, rather than providing a stable build.  I guess we can simply note that users should rely on installations from source to ensure they have either the latest version (i.e. when using CRAN mirror) or a version-stable build (i.e. via the MRAN mirror).  Installing the binaries from the PPA will do neither.  

Also, note that in general, I believe that you can mix R binaries from older versions with newer versions of R, but iirc this broke at the transition from R 3.4 to R 3.5, and `ubuntu:bionic` is stuck on 3.4.   (Note that we hope to launch these new images on yesterday's release of `ubuntu:focal` as much as possible, which is at R 3.6.3, but we may also offer older bionic builds)

**Comment by Robinlovelace** [comment]
Good response, fully agree, there is less merit to ppas for Docker images as they come pre-built. Great work on transitioning to R 4.0.0, many people will benefit, let me know if I can be of use testing/whatever.
