### ISSUE TITLE
docker image error path: /sys/fs/cgroup/memory/memory.limit_in_bytes

### ISSUE THREAD

**Issue by alexmondaini** [rocker-org/rocker-versioned2#289]
I'm using the latest docker image of rocker r_studio server on a HPC environment. Here is a link of this image.

The problem is that whenever I launch Rstudio on my server I get some sort of file missing that is related to memory:

`
[rsession-alexandre] ERROR system error 2 (No such file or directory) [path: /sys/fs/cgroup/memory/memory.limit_in_bytes]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::openForRead(std::shared_ptr<std::basic_istream >&) const src/cpp/shared_core/FilePath.cpp:1453; LOGGED FROM: rstudio_boost::shared_ptrrstudio::core::system:{anonymous}::LinuxMemoryProvider rstudio::core::system::{anonymous}::getMemoryProvider() src/cpp/core/system/LinuxResources.cpp:374`

I use the configuration Singularity file provided here through this link:

https://www.rocker-project.org/use/singularity/

**Comment by eitsupi** [comment]
This thread may help you. https://community.rstudio.com/t/rstudio-cloud-cannot-read-in-1gb-file/3197/17

**Comment by alexmondaini** [comment]
should I create the file and Rstudio server will take care of the rest ? How does it work ? I would like like to tell Rstudio to use as much memory as there is available.

**Comment by cboettig** [comment]
@alexmondaini aside from the error message, do you see any other consequences of this message?  I.e. other than this message, do you have any indication that your rstudio instance doesn't have access to the memory on  the server?

I'm guessing RStudio is trying to read the `/sys/fs/cgroup/memory/memory.limit_in_bytes` on the host but for some reason doesn't have access to that file, or is looking for it in the wrong place.  I suspect this message is more nuance noise than actual issue.

**Comment by alexmondaini** [comment]
Dear @cboettig no aside from this message I did not notice any memory constraints. What do you mean by host ? I thought since Rstudio is containerized there is no chance Rstudio can look at a different filesystem other than the container image itself. As I said previously if I go into the docker's rocker image by issuing the command `singularity shell rocker.sif` and look for the file `/sys/fs/cgroup/memory/memory.limit_in_bytes` in fact the file does not exist there. Would it be a good idea to create this file in this path and set a line decalring the memory limit in bytes ? thanks

**Comment by cboettig** [comment]
>  What do you mean by host ? I thought since Rstudio is containerized there is no chance Rstudio can look at a different filesystem other than the container image itself.
Nope, in general the docker container has it's own files, unless you volume-map (bind mount) them https://docs.docker.com/storage/volumes/.  However, singularity does things a little differently than the standard docker engine, I believe it binds a bunch of volumes automatically though as I don't really use it I'm not sure which.  Anyway, you might see if `sys/fs/cgroup/memory/memory.limit_in_bytes` exists on the host?  

I wouldn't create the file though.  It may be worth filing an issue with RStudio to ask why it is looking for that particular file.  It seems RStudio wants to know the available memory, and has decided that's the right place to look.  From a little googling it sounds like that may not be true if you use cgroup2 instead of cgroup1, e.g. https://stackoverflow.com/questions/65646317/sys-fs-cgroup-memory-memory-limit-in-bytes-not-present-in-fedora-33, though why your system does not have this file is maybe a better question for your HPC admin or singularity (perhaps singularity is using cgroup2?)  I'm a bit out my depth on that, @eddelbuettel may have deeper insight.  But anyway, the file isn't there, but it doesn't seem like it will harm anything; RStudio just wants to know the available memory limit probably because the current version shows you how much ram you're using relative to what's available.

**Comment by alexmondaini** [comment]
@cboettig  oh yes you were right, `sys/fs/cgroup/memory/memory.limit_in_bytes` exists on the host and is set to this gigantic number `9223372036854771712`

**Comment by alexmondaini** [comment]
should i bind mount this path sys/fs/cgroup/memory/ onto the container ? The host has `memory.limit_in_bytes` but the container does not have `memory.limit_in_bytes` .

**Comment by cboettig** [comment]
@alexmondaini No, I don't think binding that is a good idea.  To me, this sounds like a bug or issue you ought to report to the singularity developers.  

I think that big number is (8 exobytes) reflects that you are on 64 bit architecture, not what the HPC machine actually has available.  Typically when we create a container using the docker engine, the cgroup memory limit is set to the hardware limit, or the fraction there-of if additional memory limits are manually set.  Somehow, singularity isn't doing this, and it would be worth discussing why with them.  (If they have a good reason for this, then maybe you should also raise it with RStudio).  

but from the end-user perspective, I think you can ignore the error message as mere noise.
