### ISSUE TITLE
Default password on rocker/rstudio

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#294]
Related to #237

If we do not set the `-e PASSWORD=foobar` option when creating a new container with the `docker run` command, the `/init` command will exit halfway and RStudio Server will start without some option settings.
I think the current behavior makes little sense from a security point of view, because users may not notice the warning message and continue to use the system as it is, except when they try to set a specific option (like #237).

For example, Jupyter https://hub.docker.com/u/jupyter automatically generate a random token that the user can use to log in when started without the password setting.

If we create a container without the `-e PASSWORD=foobar` option, I think we can use the `pwgen` command to set a random password for the default user (rstudio).
Of course, if we make this change, we will also have to modify the existing documentation that says "the initial password is rstudio".

**Comment by cboettig** [comment]
Yup, I think this makes sense.  The current situation is definitely a bug, previously the startup exited instead of continuing when no password was set, but using a randomly generated password is definitely preferable and consistent with other practice.

There's the question of how to communicate the random password to the user -- I think Jupyter prints that to the logs, which seems reasonable, though possibly easy to miss if the container is started in `--detached` mode?  

Yup, the docs need updating too!

**Comment by eitsupi** [comment]
> There's the question of how to communicate the random password to the user -- I think Jupyter prints that to the logs, which seems reasonable, though possibly easy to miss if the container is started in `--detached` mode?

Definitely the password needs to be output.
Users will not be able to log in to RStudio without knowing the password, so users who have not checked the terminal will definitely notice something strange. They will probably check the logs with the `docker logs` command or look up the documentation.
