### ISSUE TITLE
Failed to initialize NVML: Driver/library version mismatch cuda11.1 with apt toolkit install

### ISSUE THREAD

**Issue by RobJY** [rocker-org/rocker-versioned2#342]
I'm getting the error: `Failed to initialize NVML: Driver/library version mismatch` when I try to run `nvidia-smi` after I've installed the nvidia toolkit via `apt` with `apt install -y nvidia-cuda-toolkit` to get `nvcc` in a container built with `FROM rocker/ml-verse:4.1.2-cuda11.1`.

Do you have any suggestions about how to fix this?

I assume that the version of `nvcc` that I'm getting from `apt` does not match the library versions already installed in the container.
Is there a variant of the rocker containers that already has `nvcc` installed?  Would it be better to install `nvcc` from nvidia binaries?

Here's a minimal Dockerfile to reproduce the issue:

```
FROM rocker/ml-verse:4.1.2-cuda11.1

ENV CUDAToolkit_ROOT=/usr/local/cuda
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64

RUN apt update && apt install -y software-properties-common

# install nvidia toolkit
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
RUN add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
RUN apt update && apt install -y nvidia-cuda-toolkit

CMD nvidia-smi
```

If this is saved as `Dockerfile` it can be built and run with the commands:
`docker build . -t test-gpu`
`docker run --gpus all test-gpu`

If I comment out the line that installs `nvidia-cuda-toolkit` it works.

**Comment by noamross** [comment]
It appears that the issue is that, in the _NVIDIA_ repositories, the package is not called `nvidia-cuda-toolkit`, but just `cuda`. So by trying to install `nvidia-cuda-toolkit`, you're getting the older versions from the central _Ubuntu_ repositories, instead.

Packages in the NVIDIA repository are listed `https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/Packages` . 

`cuda` installs quite the kitchen sink, so I ran the following to just install `nvcc` and the container ran successfully, and `nvcc --version` gave me an 11 version number.

```
FROM rocker/ml-verse:4.1.2-cuda11.1

ENV CUDAToolkit_ROOT=/usr/local/cuda
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64

RUN apt update && apt install -y software-properties-common

# install nvidia toolkit
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
RUN add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
RUN apt update && apt install -y cuda-nvcc-11-1
CMD nvidia-smi
```

**Comment by RobJY** [comment]
Ah, that's great!  Thanks so much!
