### ISSUE TITLE
save compression disabled by default

### ISSUE THREAD

**Issue by lochbika** [rocker-org/rocker-versioned2#348]
Hi,
thanks for all the great work! One rather cosmetic thing: I often save objects with the save function. However in the rocker/rstudio image compression is disabled by default. I know, it's easy to enable it with the respective option for the save function. But, I think it's such an essential thing to have compression that it should be enabled by default.

Best

**Comment by cboettig** [comment]
apologies, can you be more specific about the configuration option you would like to see changed?

**Comment by lochbika** [comment]
Yes, of course.
`save` takes the defaults for some of its options from
```
> options("save.defaults")
$save.defaults
$save.defaults$ascii
[1] FALSE

$save.defaults$compress
[1] FALSE
```
In this list the value for `$save.defaults$compress` is `FALSE`. 
It should be true, imho.

Thanks and best

**Comment by cboettig** [comment]
Thanks -- to be clear, you are suggesting we override the R default settings user-wide by providing an alternative option in `${R_HOME}/etc/Rprofile.site`?  In general I prefer to stick with the default R settings unless there is a compelling reason to alter them.  Users can easily provide their own options, as they would do with any other R installation.

In the case of the save defaults, I imagine that enabling compression by default slows down save/load behavior, which may further slow down a user's 'restore session' or other operations.  In general, design which improves interactive performance speed at the cost of a little extra disk space may be preferred (which is why many programs use data caching). 

For longer-term saving of data that might be re-used, I generally recommend users select a standard data format serialization, such as parquet or compressed csv files for tabular data, consistent with W3C recommendation and data repository best practices.  The user may also want more explicit control over compression algorithm depending on the use case, or desires to use newer compression algorithms.  In some cases, compression may be handled on the file system or object store already, so compressing in R becomes unnecessary.  

So in this case, I think it is reasonable to leave the choice to the user and stick with the upstream default behavior?

**Comment by eddelbuettel** [comment]
I am also unclear where this comes from as my system (running Ubuntu with the Ubuntu build of the standard R package in Debian) does not have the option set.  You are correct, I see it in `help(save)` but it is not clear where you may have gotten a setting from.

Also, if I may, there are compelling alternatives for to-disk serialization that compress better / faster. I just used package `fst` yesterday...

**Comment by lochbika** [comment]
Thanks for your elaborate answer! 
I am usually using the vanilla R and RStudio package from my distro (Arch Linux) and it comes with the compression enabled by default.That's why I was surprised that it is disabled in your docker image.

Some more background information:
I had a closer look, and if I am reading it correctly the documentation for [save](https://stat.ethz.ch/R-manual/R-devel/library/base/html/save.html) also sets it to `TRUE` if an object is written to a binary file. This default behavior can only be changed by explicitly setting `options("save.defaults")$compression` to `FALSE`. `options("save.defaults")$compression` returns NULL in my R installation. Also, looking at `help(options)` also makes me think that compression enabled is the default behavior since it has no default value for `options("save.defaults")` listed, meaning it will ultimately default to `NULL`.

Nevertheless, I agree, it's a rather cosmetic change since the user can activate it by giving the extra option to the save function. No change needed from my side.

Cheers

**Comment by cboettig** [comment]
:+1: AFIK we're not altering the default setting, it appears unset (`NULL`) to me.
