### ISSUE TITLE
Shift to hosting images on GitHub?

### ISSUE THREAD

**Issue by Robinlovelace** [rocker-org/rocker-versioned2#524]
### Container image name

-

### Container image digest

-

### Question

I notice that documentation increasingly points to GCR hosted versions of the images. Are there any plans to phase out Docker Hub hosted images? 

And on a different note (saving time by asking as a single question): any plans to migrate to Ubuntu 22.04 as the base image?

**Comment by Robinlovelace** [comment]
Update on this, I see the geospatial image is still based on 20.04 after running this command:

```
docker run --rm -ti rocker/geospatial 
```

Any ideas when it will be updated to 22.04? Looking at the build scripts I guess that depends on the RSPM.

**Comment by eitsupi** [comment]
> I notice that documentation increasingly points to GCR hosted versions of the images. Are there any plans to phase out Docker Hub hosted images?

The purpose is to enable the use of GHCR when a connection to DockerHub is not available. See #371.
(Of course you can use GHCR as your main registry instead of DockerHub; there is no difference in the images that are pushed.)

I see no reason to stop using DockerHub at this time.

> any plans to migrate to Ubuntu 22.04 as the base image?

Switching to `ubuntu:jammy` is tracked in #282.
The rules for version selection are documented here. https://github.com/rocker-org/rocker-versioned2/wiki/Versions

The actual Ubuntu version selected is chosen at the following line in the script.

https://github.com/rocker-org/rocker-versioned2/blob/e7c1878cc5f04033a9677a94e88115b42ed15ade/build/make-stacks.R#L441

Since it has now been more than 90 days since the release of Ubuntu 22.04, the base image will be switched in the next release, R 4.2.2.

**Comment by Robinlovelace** [comment]
Many thanks for the clarification, great news that there's no pressure to switch. Looking forward to R 4.2.2!
