### ISSUE TITLE
rserver executable not found

### ISSUE THREAD

**Issue by frederikziebell** [rocker-org/rocker-versioned2#538]
### Container image name

rocker/rstudio:4.2.1

### What operating system are you seeing the problem on?

Linux

### System information

- singularity version 3.7.0-1.el7
- linux 3.10.0-1160.11.1.el7.x86_64

### Bug description

Running the rserver command inside a singulartiy container gives a `FATAL:   "rserver": executable file not found in $PATH` error.

### How to reproduce this bug?

```sh
singularity pull docker://rocker/rstudio:4.2

singularity exec rstudio_4.2.sif rserver
```

Note: The issue does not occurr in `rocker/rstudio:4.1`.

**Comment by eitsupi** [comment]
I think we can avoid this by specifying absolute paths as like `/usr/lib/rstudio-server/bin/rserver` for now.

**Comment by frederikziebell** [comment]
When connecting to the session, i.e. opening `localhost:8787`, the server issues an error `/etc/rstudio/rsession.sh: 4: exec: rsession: not found`. @eitsupi could this be related to the same issue?

**Comment by eitsupi** [comment]
@frederikziebell Yes, this is because `/usr/lib/rstudio-server/bin` was removed from the environment variable PATH by #535.
All paths must be absolute except for `rstudio-server`, where a symbolic link was created by #535.
(It makes sense to use absolute path for `rstudio-server` as well, to be on the safe side.)

```sh
$ find /usr/lib/rstudio-server/bin -maxdepth 1 -perm -111 -type f
/usr/lib/rstudio-server/bin/crashpad_handler
/usr/lib/rstudio-server/bin/rserver-pam
/usr/lib/rstudio-server/bin/pam-helper
/usr/lib/rstudio-server/bin/crash-handler-proxy
/usr/lib/rstudio-server/bin/rpostback
/usr/lib/rstudio-server/bin/crashpad_http_upload
/usr/lib/rstudio-server/bin/rsession
/usr/lib/rstudio-server/bin/r-ldpath
/usr/lib/rstudio-server/bin/rserver
/usr/lib/rstudio-server/bin/rstudio-server
```

I made the change without knowing that singularity users use these.......

**Comment by frederikziebell** [comment]
Thanks, so I guess the fix is to just update https://github.com/rocker-org/rocker-versioned2/tree/master/scripts)/rsession.sh

**Comment by eitsupi** [comment]
@frederikziebell Are you using this file?
As discussed here (https://github.com/rocker-org/rocker-versioned2/issues/470#issuecomment-1142392541), this file is not maintained and I was thinking we should remove it.

**Comment by frederikziebell** [comment]
I don't know. I just saw that my error was related to `rsession.sh` and assumed it would be copied to `/etc/rstudio/` when the image is created. Do you know how the R session is initiated after logging in to `localhost:8787`?

**Comment by BEFH** [comment]
Is there any reason we can't just revert #535 and add `/usr/lib/rstudio-server/bin/` to `PATH` again?

**Comment by eitsupi** [comment]
> I don't know. I just saw that my error was related to `rsession.sh` and assumed it would be copied to `/etc/rstudio/` when the image is created. Do you know how the R session is initiated after logging in to `localhost:8787`?

The file `rsession.sh` does not exist in `rocker/rstudio`.
If you are using singularity with the procedure described on the following page, it seems to be defined in the following line
https://github.com/rocker-org/website/blob/cddd1b2f333018739712b3143c46beb3e4f7bc9d/use/singularity.md?plain=1#L90-L95

> Is there any reason we can't just revert #535 and add `/usr/lib/rstudio-server/bin/` to `PATH` again?

I do not want to add it to the PATH again for several reasons.

1. Since this repository divides functionality on a per-script basis, it should rely as little as possible on the PATH environment variable, which is impossible to set just by executing scripts.
  https://github.com/rocker-org/rocker-versioned2/blob/37b57ec4c419967ce7e78105464b1b1a054cfac1/README.md?plain=1#L100-L106
2. RStudio Server works fine without setting PATH.
3. To reduce the effort of definition file maintenance.

**Comment by BEFH** [comment]
That seems reasonable to me. What about symlinking rserver, and maybe 1 or
2 other relevant executables into a directory on the default search path?

**Comment by eitsupi** [comment]
> What about symlinking rserver, and maybe 1 or 2 other relevant executables into a directory on the default search path?

That's definitely a good idea, but I don't know which executables would be useful to have on the PATH (I don't use any of them).

@cboettig Any thoughts?

**Comment by frederikziebell** [comment]
@eitsupi Then it seems symlinking `rsession` in addition to `rserver` would solve the singularity issue.

**Comment by eitsupi** [comment]
> Then it seems symlinking `rsession` in addition to `rserver` would solve the singularity issue.

I am wondering if `rsession` is an executable that is intended to be run directly by the users.
If it is only used on scripts, wouldn't it just be enough to use an absolute path?

**Comment by frederikziebell** [comment]
Yes that makes sense, thanks!

**Comment by BEFH** [comment]
Personally, I would only use the rserver link, but I've migrated my recipes to use the absolute path. Maybe start with just rserver unless someone does a feature request?

**Comment by eitsupi** [comment]
Ok, I am still a bit dubious about `rserver` being on the PATH, but I made the change to add the sym link of `rserver` in the PR #541 as there seems to be a lot of demand for it.
