### ISSUE TITLE
do image have expiration date?

### ISSUE THREAD

**Issue by adrosa** [rocker-org/rocker-versioned2#542]
### Question

i was wondering if the RStudio images have a max lifetime

**Comment by cboettig** [comment]
Good question.  Roughly speaking, images should be considered viable for the lifetime for which their underlying linux distribution is supported.  For all current 4.x images, that means the lifetime of Ubuntu 20.04 LTS, which Canonical puts at April 2030.   (Note our next release, probably 4.2.2 or 4.3.0, will move to ubuntu 22.04 LTS. See https://ubuntu.com/about/release-cycle for details)

We strive to design dockerfiles that provide robust and version-stable recipes to rebuild their contents.  For the most part, this should work as long as the upstream sources (primarily RSPM snapshots for R packages, and the base ubuntu image) remain available.  Several sources (RStudio, S6 init system, a few others) come from other sources.  Most system packages come directly from the official Ubuntu LTS repositories.  (Rocker 3.x.x series images are based on Debian, which has a different lifecycle, typically 2 years, though security patches work for longer).  During the supported lifetime of the underlying distro, you should be able to both rebuild an image from scratch (i.e. by the Dockerfile recipe), and continue to use an image (and still receive security updates from upstream Ubuntu repository maintainers).  

Technically an 'image' refers to the binary built object, not the recipe, and you can often continue to "run" an image long after it can no longer be built (i.e. because upstream sources are no longer available).  You might say that images themselves have an infinite (or at least indeterminate) lifetime, i.e. that they should continue to work as long as there is a Docker runtime that supports the image specification.  Note that a given image (i.e. a specific hash, not a specific version tag) will not have security updates, and may not be compatible with external facing software if it cannot be updated (e.g. if it lacks more recent root SSL security certificates required for TLS authentication etc).

**Comment by eitsupi** [comment]
Did you solve the problem?
I will close this for now, but feel free to open it again.
