### ISSUE TITLE
Are the dockerfiles listed on Docker Hub outdated?

### ISSUE THREAD

**Issue by andburch** [rocker-org/rocker-versioned2#594]
### Question

The dockerfiles listed on the Docker Hub site seem to be outdated. For example the rocker/tidyverse (https://hub.docker.com/r/rocker/tidyverse/dockerfile) dockerfile reads as: 

```
FROM rocker/rstudio:3.6.3

RUN apt-get update -qq && apt-get -y --no-install-recommends install \
  libxml2-dev \
  libcairo2-dev \
  libsqlite-dev \
  libmariadbd-dev \
  libmariadbclient-dev \
  libpq-dev \
  libssh2-1-dev \
  unixodbc-dev \
  libsasl2-dev \
  && install2.r --error \
    --deps TRUE \
    tidyverse \
    dplyr \
    devtools \
    formatR \
    remotes \
    selectr \
    caTools \
    BiocManager

```

I know that rocker uses scripts in the dockerfiles now, but it seems like these old dockerfiles should maybe be removed from Docker Hub? They seem a bit misleading, etc, and they confused me (a total newbie) for a while. That being said, I don't know whether Docker Hub demands that dockerfiles are listed for every image, etc etc.

If you search ` "rocker/tidyverse" "dockerfile" ` in Google, it's the first link that comes up!

**Comment by eddelbuettel** [comment]
They are _versioned_ and available _on purpose_ so that someone wanting to run with R 3.6.3 could access the very container you use there.

For background on the two core stacks of the Rocker Project consider taking a look at our [R Journal paper](https://journal.r-project.org/archive/2017/RJ-2017-065/index.html).

I think this issue should be closed.
