### ISSUE TITLE
Documentation on how to override defaults and *not* install binary versions of packages?

### ISSUE THREAD

**Issue by Robinlovelace** [rocker-org/rocker-versioned2#631]
### Container image name

rocker/geospatial

### Container image digest

Not sure

### What operating system related to this question?

Linux

### System information

Not relevant

### Question

Can the documentation explain how to override the defaults to install everything from binary versions shipped by RStudio? I need to re-compile `sf` but `install.packages("sf")` fails with the following:

```
install.packages("sf")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://packagemanager.posit.co/cran/__linux__/jammy/latest/src/contrib/sf_1.0-12.tar.gz'
Content type 'binary/octet-stream' length 3498486 bytes (3.3 MB)
```

I've tried adding `type = "source"` and a few other things but the only way I got it to work was installing from GitHub with

```
remotes::install_github("r-spatial/sf")
```

I think this documentation would live well here: https://rocker-project.org/use/extending.html

Context with reproducible example you can try: https://github.com/geocompx/geocompr/issues/948#issuecomment-1500962440

**Comment by eddelbuettel** [comment]
Have you tried changing the value of `options("repos")` ?  

For this particular stack the value is considered a feauture, not a bug.

**Comment by cboettig** [comment]
@Robinlovelace thanks, yeah we should document this better -- it is annoying that RSPM snapshots don't honor `type="source"` on install.packages().  To install from source using RSPM repos you simply drop the architecture bits from the repo URL, i.e. drop the `__linux__/jammy`

```r
options(repos = "https://packagemanager.posit.co/cran/latest")
```

(or similar for the versioned snapshots.  Obviously for 'latest' installs from source you can also just point at CRAN).  Note that the `rocker/geospatial:dev-osgeo` tags do this by default, since we need to build `sf` and friends against the manually compiled latest versions of osgeo)

Where would be the most obvious place to document this?

**Comment by Robinlovelace** [comment]
Somewhere in this page was my thinking, but not sure where: https://rocker-project.org/use/extending.html

**Comment by eitsupi** [comment]
I think this is documented on this page.
https://rocker-project.org/images/versioned/r-ver.html#switch-the-default-cran-mirror

It would be very helpful if you could submit a PR for improvement on this page.

**Comment by Robinlovelace** [comment]
I'm going to give you suggestion a go @cboettig, finally:

```
options(repos = "https://packagemanager.posit.co/cran/latest")
``` 

I will tag this issue in the commits in case of use. Will try to make edits to that page also @eitsupi thanks for the suggestion.
