### ISSUE TITLE
Run jupyter as a service?

### ISSUE THREAD

**Issue by vnijs** [rocker-org/rocker-versioned2#65]
I assume the new binder Docker file is meant to override S6 and use `CMD jupyter notebook --ip 0.0.0.0`. However, I'm interested in running jupyter as an S6 service side-by-side with Rstudio etc. 

When I add the below to rocker/rstudio:4.0.0 it does work but I'd prefer to run jupyter as a regular user with a home directory etc. to avoid the screenshot below for the terminal app in jupyter. Do you have any suggestions on what would be required to make that work? When I set `USER rstudio` `docker run` fails with.

`s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied`

![image](https://user-images.githubusercontent.com/2998956/85816940-756b6e00-b721-11ea-93cd-b511dae14bb3.png)

```
#!/bin/bash

apt-get update -qq
apt-get install -y --no-install-recommends \
    software-properties-common \
    dirmngr \
    gpg-agent \
    curl \
    python3-dev \
    python3-pip

apt-get clean && rm -rf /var/lib/apt/lists/*

curl -sL https://deb.nodesource.com/setup_12.x | bash \
    && apt-get install -y nodejs \
    && npm install -g npm

pip3 install jupyterlab==2.1.4
pip3 install jupyter-server-proxy==1.5.0 jupyter-rsession-proxy==1.2 \
    && jupyter labextension install @jupyterlab/server-proxy

pip3 install bash-kernel
python3 -m bash_kernel.install

# install the R kernel for Jupyter Lab
R -e 'install.packages("IRkernel")' -e 'IRkernel::installspec(user = FALSE)'

## Set up jupyter init script
mkdir -p /etc/services.d/jupyter
echo '#!/usr/bin/with-contenv bash
## load /etc/environment vars first:
exec jupyter lab --ip=0.0.0.0 --port=8989 --allow-root --NotebookApp.token=' \
> /etc/services.d/jupyter/run
```

**Comment by cboettig** [comment]
@vnijs nice!  Yup, the container needs to be started as root so that it can run the init service to begin with.  But I think you should be able to have your jupyter launch script simply run the command as a user?   

e.g, you may able to just add an `su $USER` or something to switch user from root to your user before running `exec jupter lab ...`  (Or maybe use `runuser -l exec ...`, is the preferred linux-foo..., anyway you get the idea).  Haven't tested that myself, so let us know how it goes!

**Comment by vnijs** [comment]
Thanks for the suggestions @cboettig!

I used the below to get jupyter to run as the rstudio user. Not sure if it feasible to change this depending on the USER selected when you use `docker run ...` ?

`exec sudo -u rstudio jupyter lab --ip=0.0.0.0 --port=8989 --user=rstudio --NotebookApp.token=""' \`

I also added the below in the docker file so the terminal in jupyter starts with bash and `whoami` returns `rstudio` which is great.

`RUN echo "SHELL=/bin/bash" >> /etc/environment`

I'm still stuck in the wrong home directory however and setting environments in /etc/environment doesn't seem to help

![image](https://user-images.githubusercontent.com/2998956/85820836-ffb8cf80-b72b-11ea-9f98-89fa09eeaeee.png)

I used `supervisord` previously and there you could set relevant environment information as follow. I'm guessing S6 doesn't have something like this?

```
[program:jupyterlab]
user=%(ENV_NB_USER)s
environment=HOME=/home/%(ENV_NB_USER)s,USER=%(ENV_NB_USER)s,SHELL=/bin/bash
command=/usr/local/bin/jupyter lab --ip=0.0.0.0 --port=8989 --allow-root --NotebookApp.token='%(ENV_JPASSWORD)s'
```

Somewhat related question: Is there no way to run `init` (and rstudio-server for that matter) as a regular user? That would make combining features from https://github.com/jupyter/docker-stacks with rocker, R, and Rstudio quite a bit easier I expect

**Comment by cboettig** [comment]
Re directory, it looks like jupyter lab is just defaulting to the dir that exec was run from, so maybe a `cd` first would be in order (unless jupyter lab takes a `--dir` or something like that as an argument?)

Re RStudio-server as a regular user: the RStudio server interface supports multi-user logins, which obviously requires root-level permissions (of course you couldn't switch users inside a running container if the container itself belonged to a single user).  If multi-user support isn't important though, I believe you can by-pass the RStudio server entirely, and run an `rsession` as a single user (which is what RStudio-server runs after you've logged in).  I have an experimental shell script for doing this, see https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/rsession.sh.  You'd run that shell script as user, bypassing the whole init system, e.g. maybe

```
docker run -d -p 8787:8787 --user rstudio rocker/rstudio /rocker_scripts/rsession.sh
```

but that's untested and may still need some tweaking to work.  


I don't know what it would mean to run `init` as a user -- do any init systems, e.g. supervisord, allow for such things?  In general having an init system can be nice, particularly if you want multiple services inside the same container (e.g. shiny server, or maybe you want to have an ssh-server running inside the container so users can ssh into the container but not the host -- ssh-server is another thing that I just think is meant to run as root.  True this is not very docker-esque, but it is also true that's it's often more practical to add multiple services to the same container like you are doing here, since the shared libs are not all that 'compose-able'.  

I think at some level there's kinda a divergence of philosophy between those python data science containers -- I do understand the motivation  to put everything under non-root privileges (and install everything in `~/`, again as user, eschewing system-based installs `apt-get` etc etc) -- most people are working in single-user environments these days and the multi-user linux server may be an old model in a containerized world.  Still I think there's something to be said for standard linux model of escalating privileges and having shared libraries etc, even in single-user environments.

**Comment by eddelbuettel** [comment]
> Still I think there's something to be said for standard linux model of escalating privileges and having shared libraries etc, even in single-user environments.

Word.

**Comment by vnijs** [comment]
Thanks again for your input @cboettig. There seems be a conflict when I want be able to run Rstudio with sudo and also start it from Jupyter Hub. I had a hard time figuring what they exact issue was and ran out of time to work on it. For now I'm sticking with launching Rstudio from jypyter using `jupyter-resssion-proxy`. 

Conda does, by default install in `~/`. However, in their docker containers they  install python packages in `/opt/conda` (see link below). My impression, however, is that the official/endorsed python solution is moving towards using pyenv + pipenv. 

https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L39

@cboettig @eddelbuettel Thank you both for your work on rocker. It is a fantastic resource!
