### ISSUE TITLE
How to use the Makefile?

### ISSUE THREAD

**Issue by emilmahler** [rocker-org/rocker-versioned2#66]
Beginner question here (apologies). In the previous rocker-versioned setup, I would edit the dockerfile and run:
`docker build -f Dockerfile -t folder/geospatial .`

With rocker-versioned2, the Readme alludes to using the Makefile instead. How do I execute it? I have tried editing `scripts/install_geospatial.sh` (adding some drivers, packages and keys) and then `docker build -f Dockerfile_geospatial_4.0.0 -t folder/geospatial .` but the things I add don't get added/installed. Looking at the log, it looks like `install_geospatial.sh` is loaded from `rocker_scripts/`, a folder I don't have (but presumably the Makefile creates).

**Comment by cboettig** [comment]
@emilmahler Can you add a bit more about what you are trying to accomplish?

Even in the previous `rocker/versioned`, we would recommend you make modifications by creating a separate Dockerfile that extends a rocker image, rather than editing a rocker Dockerfile.  e.g. if you're seeking to add some packages on top of the existing `rocker/geospatial`, you might do:

```
FROM: rocker/geospatial
RUN apt-get update && apt-get -y install ...
```

The `Makefile` here is mostly for developers contributing directly to the existing stack, or wanting to build the stack from scratch, in which case you would just run `make geospatial` etc.  `rocker_scripts` is just a copy of the `scripts/` folder from this repo which is copied to `/rocker_scripts` on all the rocker-versioned images.  This makes it somewhat easier to deploy our default recipes, e.g. you can add the geospatial files to, say, `rstudio` image by:

```
FROM rocker/rstudio
RUN /rocker_scripts/install_geospatial.sh
```

But again it is not intended that you modify scripts like `install_geospatial.sh` directly.  It is much better to add your additional drivers, packages, keys etc on top as an extension.  HTH

**Comment by cboettig** [comment]
closing as resolved, thanks again for your question!
