### ISSUE TITLE
Minified images?

### ISSUE THREAD

**Issue by Robinlovelace** [rocker-org/rocker-versioned2#95]
I guess this will not yield the 10+ fold decrease in image size that some of the examples demonstrate for rocker images, but wondered if it could reduce some aspects of the base images, particularly the Ubuntu bits, to enable faster download and update times for rocker's awesome fleet: https://github.com/docker-slim/docker-slim

**Comment by eddelbuettel** [comment]
That has been proposed a few times, also in the `r-base` image stack with both things like Alpine / MUSL bring a differnt C library (ewww) or the 'slim' variants of base Ubuntu and Debian containers.  We generally say 'thanks but no thanks' as we generally want to be very faithful to the desktop experience and not modify builds.  Plus, with the larger container such such `geospatial` or `tidyverse`, the gain from, say, 100mb down to 70mb for minified tends to wash out once you are at 2gb or larger container.   Happy to be convinced otherwise so feel free to try and build some but our thinking is that it is not quite as exciting to us as advertised.

**Comment by Robinlovelace** [comment]
Good points well made. Closing as it's been suggested before. Can always be reopened if some promising results emerge.
